-- Walk In Closet: complete Supabase schema
-- Run this once in Supabase SQL Editor.
-- This resets the app tables. It does not delete auth users.

begin;

drop table if exists public.outfit_calendar cascade;
drop table if exists public.outfit_items cascade;
drop table if exists public.outfits cascade;
drop table if exists public.background_settings cascade;
drop table if exists public.wishlist cascade;
drop table if exists public.inspiration cascade;
drop table if exists public.clothing cascade;

create table public.clothing (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    item_name text not null,
    category text not null,
    color text,
    season text,
    favorite boolean not null default false,
    photo_path text,
    created_at timestamptz not null default now(),
    unique (id, user_id)
);

create table public.inspiration (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    title text not null,
    board_name text,
    notes text,
    image_path text not null,
    created_at timestamptz not null default now(),
    unique (id, user_id)
);

create table public.outfits (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    outfit_name text not null,
    occasion text,
    notes text,
    created_at timestamptz not null default now(),
    unique (id, user_id)
);

create table public.outfit_items (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    outfit_id bigint not null,
    clothing_id bigint not null,
    created_at timestamptz not null default now(),
    unique (outfit_id, clothing_id),
    foreign key (outfit_id, user_id)
        references public.outfits(id, user_id) on delete cascade,
    foreign key (clothing_id, user_id)
        references public.clothing(id, user_id) on delete cascade
);

create table public.outfit_calendar (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    outfit_id bigint not null,
    wear_date date not null,
    event_name text,
    notes text,
    created_at timestamptz not null default now(),
    foreign key (outfit_id, user_id)
        references public.outfits(id, user_id) on delete cascade
);

create table public.wishlist (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    item_name text not null,
    category text,
    color text,
    store_name text,
    price numeric(10,2),
    item_link text,
    priority text,
    notes text,
    image_path text,
    purchased boolean not null default false,
    created_at timestamptz not null default now(),
    unique (id, user_id)
);

create table public.background_settings (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    page_name text not null,
    image_path text,
    updated_at timestamptz not null default now(),
    unique (user_id, page_name)
);

alter table public.clothing enable row level security;
alter table public.inspiration enable row level security;
alter table public.outfits enable row level security;
alter table public.outfit_items enable row level security;
alter table public.outfit_calendar enable row level security;
alter table public.wishlist enable row level security;
alter table public.background_settings enable row level security;

-- Every app table follows the same ownership rule.
do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'clothing', 'inspiration', 'outfits', 'outfit_items',
        'outfit_calendar', 'wishlist', 'background_settings'
    ]
    loop
        execute format(
            'create policy %I on public.%I for select to authenticated using (auth.uid() = user_id)',
            table_name || '_select_own', table_name
        );
        execute format(
            'create policy %I on public.%I for insert to authenticated with check (auth.uid() = user_id)',
            table_name || '_insert_own', table_name
        );
        execute format(
            'create policy %I on public.%I for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id)',
            table_name || '_update_own', table_name
        );
        execute format(
            'create policy %I on public.%I for delete to authenticated using (auth.uid() = user_id)',
            table_name || '_delete_own', table_name
        );
    end loop;
end $$;

-- One private bucket holds every image. The first folder is always the user UUID.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'closet-images',
    'closet-images',
    false,
    10485760,
    array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

-- Re-running the script should not leave duplicate storage policies.
drop policy if exists "closet_images_select_own" on storage.objects;
drop policy if exists "closet_images_insert_own" on storage.objects;
drop policy if exists "closet_images_update_own" on storage.objects;
drop policy if exists "closet_images_delete_own" on storage.objects;

create policy "closet_images_select_own"
on storage.objects for select to authenticated
using (
    bucket_id = 'closet-images'
    and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "closet_images_insert_own"
on storage.objects for insert to authenticated
with check (
    bucket_id = 'closet-images'
    and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "closet_images_update_own"
on storage.objects for update to authenticated
using (
    bucket_id = 'closet-images'
    and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
    bucket_id = 'closet-images'
    and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "closet_images_delete_own"
on storage.objects for delete to authenticated
using (
    bucket_id = 'closet-images'
    and (storage.foldername(name))[1] = auth.uid()::text
);

commit;
